language: python

python:
    - "2.7"
    - "3.6"

addons:
  apt:
    packages:
      - gdb
      - python2.7-dbg
      - python3-all-dbg

install:
  - pip install --upgrade pip setuptools

script:
  - gdb --args python platform_info.py
  - gdb --args python -m ensurepip --upgrade
