language: python

python:
    - "2.7"
    - "3.6"

addons:
  apt:
    packages:
      - gdb
      - python2.7-dbg
      - python3-all-dbg

install:
  - pip install --upgrade pip setuptools

script:
  - gdb -ex quit --args python -c "import sys ; print(sys.version)"
  - gdb -ex quit --args python platform_info.py
  - gdb -ex quit --args python -m ensurepip --upgrade
  - gdb -ex quit --args pip --version
  - gdb -ex quit --args pip install requests
  - gdb -ex quit --args python -c "import requests ; print(requests.__version__)"
