language: python

python:
    - "2.7"
    #- "3.6"

addons:
  apt:
    packages:
      - gdb
      - python2.7-dbg
      - python3-all-dbg

install:
  #- true
  #- pip install --upgrade pip setuptools
  - which python
  - GDB_VERSION="gdb-7.11"
  - time wget "http://ftp.gnu.org/gnu/gdb/${GDB_VERSION}.tar.gz"
  - time tar -xvzf ${GDB_VERSION}.tar.gz
  - cd ${GDB_VERSION}
  - time ./configure --with-python=$(which python)
  - time make
  - time make install
  - gdb --version

script:
  - gdb -ex r -ex quit --args python  -c "import sys ; print(sys.version)"
  - gdb -ex r -ex quit --args python2 -c "import sys ; print(sys.version)"
  - gdb -ex r -ex quit --args python3 -c "import sys ; print(sys.version)"

  - gdb -ex r -ex quit --args python platform_info.py

  - gdb -ex quit --args "python -m ensurepip --upgrade > out.txt"
  - cat out.txt
  - gdb -ex quit --args "pip --version > out.txt"
  - cat out.txt
  - gdb -ex quit --args "pip install requests > out.txt"
  - cat out.txt
  - gdb -ex quit --args python -c "import gdb requests ; gdb.write(requests.__version__)"
  - cat out.txt
