language: python

python:
    - "2.7"
    - "3.6"

addons:
  apt:
    packages:
      - gdb
      - python2.7-dbg
      - python3-all-dbg

install:
  - true
  #- pip install --upgrade pip setuptools

script:
  - gdb -ex r --args python  -c "import sys ; print(sys.version)"
  - gdb -ex r --args python2 -c "import sys ; print(sys.version)"
  - gdb -ex r --args python3 -c "import sys ; print(sys.version)"

  - gdb -ex quit --args python -c "import gdb sys ; gdb.write(sys.version)"
  - gdb -ex quit --args python -c "import gdb sys ; gdb.write(sys.version)"
  - gdb -ex quit --args python -c "import gdb sys ; gdb.write(sys.version)"

  - gdb -ex r --args python platform_info.py

  - gdb -ex quit --args "python -m ensurepip --upgrade > out.txt"
  - cat out.txt
  - gdb -ex quit --args "pip --version > out.txt"
  - cat out.txt
  - gdb -ex quit --args "pip install requests > out.txt"
  - cat out.txt
  - gdb -ex quit --args python -c "import gdb requests ; gdb.write(requests.__version__)"
  - cat out.txt
