# https://stackoverflow.com/questions/26910649/unable-to-install-gdb-with-python-support

sudo: required
group: travis_latest
language: python

python:
    - "2.7"
    #- "3.6"

addons:
  apt:
    packages:
      #- cmake
      #- g++
      #- gcc
      #- git
      #- libglib2.0-dev
      #- pkg-config
      #- gdb
      #- gdb-python2
      - python2.7-dbg
      - python3-all-dbg
      - python-pip
      #- python3-pip
      - texinfo

install:
  #- true
  #- pip install --upgrade pip setuptools
  #- pip install requests  # later try '(gdb) py import requests ; print(requests.version)'
  - which python  # /home/travis/virtualenv/python2.7.14/bin/python
  - which python2  # /home/travis/virtualenv/python2.7.14/bin/python
  - which python3  # /home/travis/virtualenv/python2.7.14/bin/python
  #- which python  # /home/travis/virtualenv/python2.7.14/bin/python
  - GDB_VERSION="gdb-8.1"
  - wget "http://ftp.gnu.org/gnu/gdb/${GDB_VERSION}.tar.xz"
  - tar -xJf ${GDB_VERSION}.tar.xz
  - cd ${GDB_VERSION}
  - export LDFLAGS=-L$(python -c "print(sys.path[0])")
  - echo ${LDFLAGS}
  - ./configure --with-python=$(which python)  # /home/travis/virtualenv/python2.7.14/bin/python
  - sudo make
  - sudo make install
  - gdb --version
  - gdb -ex "show configuration" -ex quit | grep python
  - gdb -ex "py import sys ; print(sys.executable, sys.version)" -ex quit
  #- gdb -ex "py import requests ; print(requests.__version__)" -ex quit
  #- gdb-python2 -ex "show configuration" -ex quit | grep python
  - /usr/bin/python2.7 -m pip --version
  - sudo /usr/bin/python2.7 -m pip install --upgrade pip
  - /usr/bin/python2.7 -m pip install --upgrade requests
  - gdb -ex "py import requests ; print(requests.__version__)" -ex quit

script:
  - gdb -ex r -ex quit --args python  -c "import sys ; print(sys.version)"
  - gdb -ex r -ex quit --args python2 -c "import sys ; print(sys.version)"
  - gdb -ex r -ex quit --args python3 -c "import sys ; print(sys.version)"

  - gdb -ex r -ex quit --args python platform_info.py

  - gdb -ex quit --args "python -m ensurepip --upgrade > out.txt"
  - cat out.txt
  - gdb -ex quit --args "pip --version > out.txt"
  - cat out.txt
  - gdb -ex quit --args "pip install requests > out.txt"
  - cat out.txt
  - gdb -ex quit --args python -c "import gdb requests ; gdb.write(requests.__version__)"
  - cat out.txt
